---
title: "Combined ETL"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(warning = F,
                      message = F,
                      echo = F)

library(ggplot2)
library(reader)
library(ggthemes)
library(knitr)
library(rmarkdown)
library(dplyr)
library(tidyr)
library(lubridate)
library(stringr)
library(shiny)
library(shinydashboard)
library(dashboardthemes)
library(shinyWidgets)
library(forcats)
library(readr)
library(readxl)
library(tibble)
library(kableExtra)
library(gt)

```

```{r}

# big_comm <- read_csv(file = "Data\\2021-01-07-bc-orders.csv")

big_comm_prods_line_classified <- read_csv(file = "Data\\2021-01-07-bc-orders.csv") %>%
# tt <- big_comm %>%  # For Testing
  # slice(1:100) %>%  # For Testing
  rename_all(~ tolower(x = .)) %>%
  rename_all(~ gsub(pattern = " ", replacement = "_", x = .)) %>% 
  rename_all(~ gsub(pattern = "-", replacement = "_", x = .)) %>% 
  rename_all(~ gsub(pattern = "(", replacement = "", x = ., fixed = T)) %>% 
  rename_all(~ gsub(pattern = ")", replacement = "", x = ., fixed = T)) %>% 
  mutate(customer_email_lower = str_to_lower(string = customer_email),
         order_date = dmy(order_date),
         order_id = as.character(order_id)) %>% 
  select(order_id, customer_email_lower, order_date, order_total_inc_tax, product_details) %>% 
  separate(col = product_details,
           into = c("product1", "product2", "product3", "product4", "product5", "product6", "product7", "product8", "product9"),
           sep = "\\|",
           remove = T) %>% 
  select(-order_total_inc_tax) %>% 
  gather(key = "product_num", value = "product", -c(order_id, customer_email_lower, order_date)) %>% 
  filter(!is.na(product)) %>% 
  mutate(prod_status = case_when(
    str_detect(string = product, pattern = "1c-") ~ "membership",
    str_detect(string = product, pattern = "ot-") ~ "one-time",
    TRUE ~ "Other"
  )) %>% 
  rowwise() %>% 
  mutate(product_price = as.double(str_remove_all(string = str_split(string = str_split(string = product, 
                                                                                        pattern = ",")[[1]][length(str_split(string = product, 
                                                                                                                             pattern = ",")[[1]])], 
                                                                     pattern = ":", n = 2)[[1]][2], 
                                                  pattern = "[:space:]"))) %>% 
  ungroup() %>% 
  group_by(order_id, customer_email_lower) %>% 
  mutate(order_classification = case_when(
    any(prod_status == "membership") ~ "membership",
    any(prod_status == "one-time") ~ "one-time",
    TRUE ~ "Other")) %>% 
  ungroup() %>% 
  group_by(order_id, customer_email_lower, prod_status) %>% 
  mutate(product_sub_group = max(product_price, na.rm = T)) %>% 
  ungroup() %>% 
  mutate(product_sub_group = if_else(condition = prod_status == order_classification, 
                                     true = product_sub_group,
                                     false = 9999999),
         product_sub_group = na_if(product_sub_group, 9999999)) %>% 
  group_by(order_id, customer_email_lower) %>% 
  fill(product_sub_group, .direction = "down") %>% 
  fill(product_sub_group, .direction = "up") %>% 
  ungroup() %>% 
  select(order_id, customer_email_lower, order_classification, product_sub_group) %>% 
  arrange(order_id, customer_email_lower, order_classification) %>% 
  distinct(order_id, customer_email_lower, .keep_all = T) %>% 
  filter(order_classification %in% c("membership", "one-time"))

```


```{r}

big_comm <- read_csv(file = "Data\\2021-01-07-bc-orders.csv") %>% 
  rename_all(~ tolower(x = .)) %>%
  rename_all(~ gsub(pattern = " ", replacement = "_", x = .)) %>% 
  rename_all(~ gsub(pattern = "-", replacement = "_", x = .)) %>% 
  rename_all(~ gsub(pattern = "(", replacement = "", x = ., fixed = T)) %>% 
  rename_all(~ gsub(pattern = ")", replacement = "", x = ., fixed = T)) %>% 
  mutate(order_date = dmy(order_date),
         order_id = as.character(order_id)) %>% 
  select(order_id, customer_email, order_date, order_total_inc_tax, product_details) %>% 
  rename(order_total = "order_total_inc_tax") %>% 
  mutate(file_source = "BigcommerceOrders.csv") %>% 
  rowwise() %>% 
  mutate(product_price = as.double(str_remove_all(string = str_split(string = str_split(string = product_details, 
                                                                                        pattern = ",")[[1]][length(str_split(string = product_details, 
                                                                                                                             pattern = ",")[[1]])], 
                                                                     pattern = ":", n = 2)[[1]][2], 
                                                  pattern = "[:space:]"))) %>% 
  ungroup() %>% 
  mutate(product_price = case_when(
    str_detect(string = product_details, pattern = "Product ID: 3805|Product ID: 5100|Product ID: 4295|Product ID: 3798|Product ID: 3805") ~ 10,
    str_detect(string = product_details, pattern = "Product ID: 3797") ~ 5,
    str_detect(string = product_details, pattern = "Product ID: 3799") ~ 15,
    str_detect(string = product_details, pattern = "Product ID: 3966") ~ 50,
    str_detect(string = product_details, pattern = "Product ID: 3800|Product ID: 5104") ~ 25,
    TRUE ~ product_price))

# Commented out but leaving in just in case Bold ever comes up again

# bold_v1 <- read_csv(file = "Data\\Boldv1.csv") %>% 
#   rename_all(~ tolower(x = .)) %>%
#   rename_all(~ gsub(pattern = " ", replacement = "_", x = .)) %>% 
#   rename_all(~ gsub(pattern = "-", replacement = "_", x = .)) %>% 
#   select(subscription_id, customer_e_mail, 
#          inactive_date,  
#          subscription_date, products, total_value_of_all_products_shipped) %>% 
#   mutate(subscription_date = mdy(subscription_date),
#          inactive_date = mdy(inactive_date)) %>% 
#   rename(order_date = "subscription_date",
#          customer_email = "customer_e_mail",
#          order_total = "total_value_of_all_products_shipped",
#          product_details = "products",
#          canceled_date = "inactive_date",
#          order_id = "subscription_id") %>% 
#   mutate(order_id = as.character(order_id),
#          file_source = "Boldv1.csv") %>% 
#   rowwise() %>% 
#   mutate(product_price = 
#            as.double(str_remove_all(string = str_split(string = 
#                                                          str_split(string = product_details, pattern = "-")[[1]][length(str_split(string = product_details,
#                                                                                                                                   pattern = "-")[[1]])], 
#                                                        pattern = "x")[[1]][1], pattern = "[:space:]"))) %>% 
#   ungroup()

# bold_v2 <- read_csv(file = "Data\\Boldv2.csv") %>%   # Maybe skip this for now since it's missing the product??
# # tt <- bold_v2 %>%
#   rename_all(~ tolower(x = .)) %>%
#   rename_all(~ gsub(pattern = " ", replacement = "_", x = .)) %>%
#   rename_all(~ gsub(pattern = "-", replacement = "_", x = .)) %>%
#   rename_all(~ gsub(pattern = "/", replacement = "_", x = ., fixed = T)) %>%
#   mutate(products = "None in file") %>% 
#   select(subscription_id, customer_email, created_at,
#          canceled_at,  # Maybe need - think about it
#          products,  # Not finding this
#          total_value_charged) %>% 
#   mutate(created_at = ymd_hms(created_at),
#          created_at = date(created_at),
#          canceled_at = ymd_hms(canceled_at),
#          canceled_at = date(canceled_at)) %>% 
#   rename(order_date = "created_at",
#          customer_email = "customer_email",
#          order_total = "total_value_charged",
#          product_details = "products",
#          canceled_date = "canceled_at",
#          order_id = "subscription_id") %>%
#   mutate(order_id = as.character(order_id),
#          file_source = "Boldv2.csv") %>% 
#   mutate(product_price = 10)

give_orders <- read_csv(file = "Data\\2022-01-07_Give.csv") %>% 
  rename_all(~ tolower(x = .)) %>%
  rename_all(~ gsub(pattern = " ", replacement = "_", x = .)) %>% 
  rename_all(~ gsub(pattern = "-", replacement = "_", x = .)) %>% 
  select(id, email, created_at, lineitem_name, total, lineitem_price) %>% 
  mutate(created_at = ymd(str_sub(string = created_at, start = 1, end = 10)),
         id = format(id, scientific = F)) %>% 
  rename(customer_email = "email",
         order_date = "created_at",
         product_details = "lineitem_name",
         order_total = "total",
         order_id = "id",
         product_price = "lineitem_price") %>% 
  mutate(order_id = as.character(order_id),
         file_source = "GiveOrders.csv") %>% 
  filter(!is.na(product_price))  

# Leaving in if MiniBC ever comes up again

# mini_bc <- read_csv(file = "Data\\MiniBC.csv") %>% 
#   rename_all(~ tolower(x = .)) %>%
#   rename_all(~ gsub(pattern = " ", replacement = "_", x = .)) %>% 
#   rename_all(~ gsub(pattern = "-", replacement = "_", x = .)) %>% 
#   rename_all(~ gsub(pattern = "/", replacement = "_", x = ., fixed = T)) %>% 
#   select(email_address, signup_date, product_name, charge_total, product_price) %>% 
#   mutate(signup_date = date(mdy_hm(signup_date))) %>% 
#   rename(customer_email = "email_address",
#          order_date = "signup_date",
#          order_total = "charge_total",
#          product_details = "product_name") %>% 
#   add_rownames(var = "order_id") %>%  # No ID found in this source, making one up from row number
#   mutate(order_id = as.character(order_id),
#          file_source = "MiniBC.csv")

shopify <- read_csv(file = "Data\\2022-01-07_Shopify.csv") %>% 
  rename_all(~ tolower(x = .)) %>%
  rename_all(~ gsub(pattern = " ", replacement = "_", x = .)) %>% 
  rename_all(~ gsub(pattern = "-", replacement = "_", x = .)) %>% 
  select(id, email, created_at, lineitem_name, total, lineitem_price) %>% 
  mutate(created_at = date(with_tz(time = ymd_hms(created_at), tzone = "America/Chicago")),
         id = format(id, scientific = F)) %>% 
  rename(customer_email = "email",
         order_date = "created_at",
         order_total = "total",
         product_details = "lineitem_name",
         order_id = "id",
         product_price = "lineitem_price") %>% 
  mutate(order_id = as.character(order_id),
         file_source = "ShopifyOrders.csv")

platform_data <- bind_rows(big_comm, 
                           # bold_v1, bold_v2, 
                           give_orders, 
                           # mini_bc, 
                           shopify) %>% 
  mutate(customer_email_lower = str_to_lower(string = customer_email)) %>%   # Unique customers based on this
  mutate(yr_mo_order = ymd(paste(year(order_date), month(order_date), "1", sep = "-")))

```

## Classify Product Cohorts

```{r}

alt_entry_customers <- read_csv(file = "Data\\AlternateEntryCustomers.csv") %>% 
  rename_all(~ tolower(x = .)) %>%
  rename_all(~ gsub(pattern = " ", replacement = "_", x = .)) %>% 
  rename_all(~ gsub(pattern = "-", replacement = "_", x = .)) %>% 
  select(email, klaviyo_id, profile_created_on) %>% 
  mutate(email = str_to_lower(string = email))

bonus_entry_leads <- read_csv(file = "Data\\BonusEntryCustomers.csv") %>% 
  rename_all(~ tolower(x = .)) %>%
  rename_all(~ gsub(pattern = " ", replacement = "_", x = .)) %>% 
  rename_all(~ gsub(pattern = "-", replacement = "_", x = .)) %>% 
  select(email, profile_created_on, total_customer_lifetime_value) %>% 
  mutate(email = str_to_lower(string = email))

products_classified <- read_csv(file = "Data\\ProductsClassified.csv") %>% 
  rename_all(~ tolower(x = .)) %>%
  rename_all(~ gsub(pattern = " ", replacement = "_", x = .)) %>% 
  rename_all(~ gsub(pattern = "-", replacement = "_", x = .)) %>% 
  mutate(grp = case_when(
    str_detect(string = classification, pattern = "Member") ~ "Member",
    str_detect(string = classification, pattern = "bonus") ~ "Bonus",
    str_detect(string = classification, pattern = "One-time") ~ "One-time",
    TRUE ~ "Other")) %>% 
  mutate(grp = case_when(
    str_detect(string = product_details, pattern = "Product ID: 3805|Product ID: 5100|Product ID: 4295|Product ID: 3798|Product ID: 3797|Product ID: 3799|Product ID: 3966|Product ID: 3800|Product ID: 5104") ~ "Member",
    TRUE ~ grp
  ))

platform_data_classified <- platform_data %>% 
  filter(!(product_details %in% c(products_classified$product_details[products_classified$grp == "Bonus"]))) %>%  # Excluding bonus products
  filter(!(str_detect(string = product_details, pattern = fixed("One Country Membership [First Month Free]")))) %>% 
  mutate(alt_entry = if_else(condition = customer_email_lower %in% c(alt_entry_customers$email),
                             true = "Yes",
                             false = "No"),
         customer_entry = case_when(
           customer_email_lower %in% c(alt_entry_customers$email) ~ "alt_entry",
           customer_email_lower %in% c(bonus_entry_leads$email) ~ "bonus_entry",
           TRUE ~ "Other"
         ),
         grp = case_when(
           product_details %in% c(products_classified$product_details[products_classified$grp == "Member"]) ~ "Member",
           product_details %in% c(products_classified$product_details[products_classified$grp == "One-time"]) ~ "One-time",
           TRUE ~ "Other"
         )) %>% #,
  left_join(x = ., y = big_comm_prods_line_classified, by = c("order_id", "customer_email_lower")) %>% 
  mutate(grp = if_else(condition = !is.na(order_classification),
                       true = order_classification,
                       false = grp),
         product_price = if_else(condition = !is.na(product_sub_group),
                                 true = product_sub_group,
                                 false = product_price),
         order_total = if_else(condition = is.na(order_total),
                               true = product_price,
                               false = order_total)) %>% 
  filter(!(product_price == 0 & order_total == 0)) %>%  
  select(-c(order_classification, product_sub_group)) %>% 
  mutate(sub_grp = case_when(
    grp == "Member" & product_price %in% c(5.00) ~ "$5",
    (grp == "Member" & product_price %in% c(10.00)) | file_source == "Boldv2.csv" ~ "$10",
    grp == "Member" & product_price %in% c(24.99, 25.00, 25.98) ~ "$25",
    grp == "One-time" & product_price %in% c(10.00) ~ "$10",
    grp == "One-time" & product_price %in% c(24.99, 25.00, 25.98) ~ "$25",
    grp == "One-time" & product_price %in% c(49.95, 49.99, 50.00, 50.96) ~ "$50",
    grp == "One-time" & product_price %in% c(99.95, 99.96, 100.00, 100.99) ~ "$100",
    grp == "alt_entry" & product_price %in% c(5.00) ~ "$5",
    grp == "alt_entry" & product_price %in% c(10.00) ~ "$10",
    grp == "alt_entry" & product_price %in% c(12.00, 12.99) ~ "$12",
    grp == "alt_entry" & product_price %in% c(15.00, 15.99) ~ "$15",
    TRUE ~ "Other"
  ),
  sales_status = if_else(condition = product_details %in% c(products_classified$product_details[products_classified$classification == "Product"]),
                         true = "Product",
                         false = "Other"))

```

## Classify All Purchases According to Customer First Transaction

```{r}

platform_data_cohorts <- platform_data_classified %>%
# yy <- platform_data_classified %>%   # For testing
  # Don't think I need this part anymore - leave in as reference in case file source is ever relevant again
  # filter(file_source %in% c("BigcommerceOrders.csv" , "GiveOrders.csv" , "ShopifyOrders.csv")) %>%
  
  # For testing individual emails
  
  # filter(customer_email_lower %in% c(
  #   "a.e.flynn@hotmail.com",
  #   "aaronj.garnica@gmail.com"
  #   )) %>% 
  arrange(customer_email_lower, order_date) %>% 
  group_by(customer_email_lower) %>% 
  mutate(customer_transaction_number_classify = if_else(condition = grp %in% c("Member", "One-time"), 
                                                        true = row_number(),
                                                        false = as.integer(0)),
         customer_transaction_number_classify = na_if(customer_transaction_number_classify, 0),
         customer_transaction_number = row_number(),
         customer_sub_group_transaction_number_classify = if_else(condition = grp == "Member",
                                                                  true = row_number(),
                                                                  false = as.integer(0)),
         customer_sub_group_transaction_number_classify = na_if(customer_sub_group_transaction_number_classify, 0),
         min_customer_sub_group_transaction_number_classify = min(customer_sub_group_transaction_number_classify, na.rm = T),
         first_customer_order = min(customer_transaction_number_classify, na.rm = T),
         min_transaction_date = min(order_date, na.rm = T)) %>% 
  ungroup() %>% 
  mutate(first_order_date = if_else(condition = customer_transaction_number_classify == first_customer_order,
                                    true = order_date,
                                    false = ymd("2099-1-1")),
         first_order_date = na_if(first_order_date, ymd("2099-1-1")),
         cohort_grp = if_else(condition = customer_transaction_number_classify == first_customer_order,
                              true = grp,
                              false = ""),
         cohort_grp = na_if(cohort_grp, ""),
         cohort_sub_grp = if_else(condition = customer_transaction_number_classify == first_customer_order,
                                  true = sub_grp,
                                  false = ""),
         cohort_sub_grp = na_if(cohort_sub_grp, "")) %>% 
  group_by(customer_email_lower, order_date) %>%
  mutate(cohort_grp = if_else(condition = order_date == min_transaction_date & any(grp == "Member"),
                              true = "Member",
                              false = cohort_grp),
         cohort_sub_grp = if_else(condition = any(grp == "Member") &
                                    customer_sub_group_transaction_number_classify == min_customer_sub_group_transaction_number_classify &
                                    !is.infinite(min_customer_sub_group_transaction_number_classify)
                                  & order_date == min_transaction_date,
                                  true = sub_grp,
                                  false = cohort_sub_grp)) %>%
  ungroup() %>%
group_by(customer_email_lower) %>%   
  fill(first_order_date, .direction = "down") %>% 
  fill(cohort_grp, .direction = "down") %>% 
  fill(cohort_sub_grp, .direction = "down") %>% 
  fill(first_order_date, .direction = "up") %>% 
  fill(cohort_grp, .direction = "up") %>% 
  fill(cohort_sub_grp, .direction = "up") %>% 
  ungroup() %>% 
  mutate(cohort = if_else(condition = customer_transaction_number_classify == first_customer_order, 
                          true = paste0(cohort_grp, " ", month(order_date, label = T), "/", year(order_date)),
                          false = ""),
         cohort = na_if(cohort, "")) %>% 
  group_by(customer_email_lower) %>% 
  fill(cohort, .direction = "down") %>% 
  fill(cohort, .direction = "up") %>% 
  mutate(total_transactions = max(customer_transaction_number),
         max_transaction_date = max(order_date, na.rm = T),
         yr_mo_first_order = ymd(paste(year(first_order_date), month(first_order_date), "1", sep = "-"))) %>% 
  fill(max_transaction_date, .direction = "down") %>% 
  ungroup() %>% 
  mutate(transaction_within_past_60_days = if_else(condition = max_transaction_date > (Sys.Date() - 60),
                                                   true = "Yes",
                                                   false = "No"),
         customer_lost = if_else(condition = customer_transaction_number == total_transactions & transaction_within_past_60_days == "No",
                                 true = "Lost",
                                 false = "Retained")) %>% 
  rowwise() %>% 
  mutate(months_since_first_purchase = interval(first_order_date, order_date) %/% months(1)) %>% 
  ungroup() %>% 
  filter(months_since_first_purchase >= 0) %>% 
  filter(!(cohort_grp == "Member" & str_detect(string = cohort, pattern = "One-time")))

write_csv(platform_data_cohorts,
          path = "Output Data\\cohorts_classified.csv")

```



```{r}

# Use if not writing data at the time of transformation

# write_csv(platform_data_cohorts,
#           path = "Output Data\\cohorts_classified.csv")

```

## Classify Membership Cohorts

Basically run everything before line 300 in chort_analysis. Then go from here. 

```{r}

member_cohorts <- platform_data_classified %>%
# tt <- platform_data_classified %>%
  
  # FOR TESTING #
  
  # filter(customer_email_lower == "abeboyd77@yahoo.com") %>%
  
  ###############

  filter(grp == "Member") %>% 
  filter(!(str_detect(string = product_details, pattern = "ot-"))) %>% 
  
  arrange(customer_email_lower, product_details, order_date) %>%
  group_by(customer_email_lower, product_details) %>%
  mutate(customer_transaction_number = row_number(),
         customer_sub_group_transaction_number = row_number(),
         min_transaction_date = min(order_date, na.rm = T)) %>% 
  ungroup() %>%
  mutate(cohort_grp = if_else(condition = order_date == min_transaction_date,
                              true = grp,
                              false = ""),
         cohort_grp = na_if(cohort_grp, ""),
         cohort_sub_grp = if_else(condition = order_date == min_transaction_date,
                                  true = sub_grp,
                                  false = ""),
         cohort_sub_grp = na_if(cohort_sub_grp, "")) %>%
  group_by(customer_email_lower, product_details) %>% 
  fill(cohort_grp, .direction = "down") %>%
  fill(cohort_sub_grp, .direction = "down") %>%
  fill(cohort_grp, .direction = "up") %>%
  fill(cohort_sub_grp, .direction = "up") %>%
  ungroup() %>% 
  mutate(cohort = if_else(condition = order_date == min_transaction_date,
                          true = paste0(cohort_grp, " ", month(order_date, label = T), "/", year(order_date)),
                          false = ""),
         cohort = na_if(cohort, "")) %>%
  group_by(customer_email_lower, product_details) %>%  
  fill(cohort, .direction = "down") %>%
  fill(cohort, .direction = "up") %>%
  mutate(total_transactions = max(customer_transaction_number),
         max_transaction_date = max(order_date, na.rm = T),
         yr_mo_first_order = ymd(paste(year(min_transaction_date), month(min_transaction_date), "1", sep = "-"))) %>%
  fill(max_transaction_date, .direction = "down") %>%
  ungroup() %>%
  mutate(membership_lost = if_else(condition = max_transaction_date == order_date,
                                   true = "Lost",
                                   false = "Retained")) %>% 
  rowwise() %>%
  mutate(months_since_first_purchase = interval(min_transaction_date, order_date) %/% months(1)) %>%
  ungroup() %>%
  filter(months_since_first_purchase >= 0) #%>% 

write_csv(member_cohorts,
          path = "Output Data\\membership_cohorts.csv")

```


```{r}

# Use if not writing data at the time of transformation

# write_csv(member_cohorts,
          # path = "Output Data\\membership_cohorts.csv")

```


























